# Generated by Django 4.0.1 on 2023-10-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserXXX',
        ),
    ]
